---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integrationtests
spec:
  args:
    - name: succeed
  metrics:
    - name: integrationtests
      failureLimit: 1
      provider:
        job:
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - name: integrationtests
                    image: pingserver:rollback
                    command: ["integrationtests"]
                    args: ["-succeed", "{{args.succeed}}"]
                restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pingserver
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 30
        - analysis:
            templates:
              - templateName: integrationtests
            args:
              - name: succeed
                value: "false"
        - setWeight: 60
        - analysis:
            templates:
              - templateName: integrationtests
            args:
              - name: succeed
                value: "false"
  selector:
    matchLabels:
      app: pingserver
  template:
    metadata:
      labels:
        app: pingserver
    spec:
      containers:
        - name: pingserver
          image: pingserver:rollback
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
